# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170907_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
